name: Sk-IDE
version: '0.0'
summary: IDE for Skript
description: ...

confinement: devmode

apps:
  run:
    command: desktop-launch java -jar -Duser-home=$SNAP_USER_DATA $SNAP/jar/Sk-IDE.jar

parts:
  Sk-IDE:
    after: [desktop-glib-only]
    plugin: gradle
    source: .
    gradle-output-dir: build/libs
    build: |
      export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
      gradle shadowJar
    install : |
      mkdir $SNAPCRAFT_PART_INSTALL/jar
      cp build/libs/Sk-IDE.jar $SNAPCRAFT_PART_INSTALL/jar/Sk-IDE.jar
    build-packages:
      - openjdk-8-jdk
      - openjfx
    stage-packages:
      - openjdk-8-jdk
      - openjfx
